/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Planet.glb --transform 
Files: public/models/Planet.glb [18.74MB] > C:\Users\devch\Downloads\3d-portfolio-main\3d-portfolio-main\Planet-transformed.glb [857.85KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Planet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} rotation={[0, 0, 0.741]} />
      <mesh geometry={nodes.Ring.geometry} material={materials['Material.001']} rotation={[-0.124, 0.123, -0.778]} scale={2} />
    </group>
  )
}

useGLTF.preload('/Planet-transformed.glb')
